### ISSUE TITLE
Выпилить реализацию ExcelTable

### ISSUE THREAD

**Issue by Ar4eR-ValerA** [kysect/SeaInk#30]
- [ ] Пересмотреть логику создания дефолтного листа (дефолтный лист обязателен) 
[Комментарий](https://github.com/kysect/SeaInk/pull/29#discussion_r621884176)
 - [ ] Попробовать переделать переименование файла
[Комментарий 1](https://github.com/kysect/SeaInk/pull/29/files/f1abd18ec42665d2baf59f898a279277238665eb#r619872252)
[Комментарий 2](https://github.com/kysect/SeaInk/pull/29#discussion_r621885275)
 - [x] Переделать логику кастов в шаблонном GetValue 
[Комментарий](https://github.com/kysect/SeaInk/pull/29#discussion_r621886525)
- [x]  Добавить новый метод иттерирования по строкам для GetValues
[Комментарий](https://github.com/kysect/SeaInk/pull/29#discussion_r621888319)

**Comment by Bibletoon** [comment]
Свободно?

**Comment by annchous** [comment]
> Свободно?

Да

**Comment by Ar4eR-ValerA** [comment]
@Bibletoon Там после последнего мерджа добавилось пара методов, которые не имплиментированы. Можешь их тоже допилить, если будет время)
Если что пиши, я скажу о каких именно методах идёт речь и что это за методы.

**Comment by FrediKats** [comment]
Обсудили, что нужно отпилить Excel.
