### ISSUE TITLE
Реализовать получение токена от гугла с пермишенами на гугл диск

### ISSUE THREAD

**Issue by FrediKats** [kysect/SeaInk#4]

**Comment by ronimizy** [comment]
Пока приложение, используемое для взаимодействия с апишками в тестовом режиме, авторизовываться через него могут только добавленные пользователи, но как только оно будет опубликовано, то любой кому будет дана возможность авторизоваться - сможет это сделать.
Так что эта ишуя фактически выполнена.

**Comment by ronimizy** [comment]
@FrediKats думаю это можно закрыть, всвязи с выше написанным

**Comment by FrediKats** [comment]
Resolved by #28
