### ISSUE TITLE
Доработать дизайн Google таблиц

### ISSUE THREAD

**Issue by Ar4eR-ValerA** [kysect/SeaInk#64]
1. Сделать столбцы с баллами узкими, под ширину названия работы
2. Сделать столбец со студентами широкими, чтобы ФИО студента влезало в одну строку.
3. Проработать ширину обводок разных столбцов, а также окантовку всей таблицы.
4. Возможно добавить где-то заголовки (например для дедлайнов).
5. Сделать таблицу красивой и информативной на свой вкус.

P.S. Так выглядит таблица на момент создания ишуи.
![image](https://user-images.githubusercontent.com/60439555/131229046-54ea8892-e4fd-45df-bf07-da6993cc85e0.png)

**Comment by ronimizy** [comment]
Irrelevant
